# -*- coding: utf-8 -*-
"""style_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOoCoig8KuISl2jkKw71C3Fx_kcVrzFF

## Google Driveからマウント
"""

from google.colab import drive
drive.mount('/content/gdrive')

!ls ./gdrive/'My Drive'/"Colab Notebooks"

"""### データセット移動"""

ls ./gdrive/'My Drive'/"Colab Notebooks"/'アップロードするデータ'

#今いるディレクトリにデータをコピーする

!cp ./gdrive/'My Drive'/'Colab Notebooks'/'アップロードするデータ'/'smile_all.txt' ./smile_all.txt

ls

"""## テキストの抜き出し"""

import sys
import numpy as np

text = open("smile_all.txt").readlines()
conv = []
np.array(conv)

#「」内のデータを1行ずつ抜き出していく
for line in text:
  char_name = line[:line.find("「")]
  char_conv = line[line.find("「")+1:line.find("」")] 
  conv.append([char_name,char_conv])

"""### 発話文(指定のキャラのセリフの1文前)と応答文(指定のキャラのセリフ)を配列に格納"""

len(conv)

#対話文で学習するときの配列型にしたもの

import re
char_t = []
np.array(char_t)


#指定のキャラクターの文を応答文、その1つ前の文章を発話文として扱う
for i in range(len(conv)):
  if(re.search(r'キャラクター名*',str(conv[i][0]))): #キャラクター名の後に「*」を付ける
    input = conv[i-1][1]
    output = conv[i][1]
    char_t.append([[input],[output]])

char_t

len(char_t)

"""## 対話文データをnpyファイルで保存

### npy形式で保存
"""

#npy形式で保存

style_char = '' #保存したいファイル名を入力(拡張子は.npy)
np.save(style_char, char_t)

ls

"""### Google Drive上にファイルを保存"""

import google.colab
import googleapiclient.discovery
import googleapiclient.http

data_npy = style_char #保存したいデータ


google.colab.auth.authenticate_user()
drive_service = googleapiclient.discovery.build('drive', 'v3')

saving_filename = data_npy #セーブしたいファイル名

file_metadata = {
  'name': saving_filename,
  'mimeType': 'application/octet-stream'
}
media = googleapiclient.http.MediaFileUpload(saving_filename, 
                        mimetype='application/octet-stream',
                        resumable=True)
created = drive_service.files().create(body=file_metadata,
                                       media_body=media,
                                       fields='id').execute()

!mkdir -p drive
!google-drive-ocamlfuse drive